mitre/training

app/flags/advanced/flag_1.py
app/flags/adversaries/flag_0.py
app/flags/adversaries/flag_1.py
app/flags/agents/flag_1.py
app/flags/agents/flag_2.py
app/flags/agents/flag_3.py
app/flags/agents/flag_4.py
app/flags/agents/flag_5.py
app/flags/operations/flag_0.py
app/flags/operations/flag_1.py
app/flags/operations/flag_2.py
app/flags/plugins/compass/flag_0.py
app/flags/plugins/manx/flag_0.py

Changes: 
* Remove trailing white space (flake8)

remove trailing whitespace

---

.flake8
.travis.yml

- Re-add working travis configuration
- Adds .flake8 for project-level linter configuration across all development platforms and testing environments

Add CI and lint configuration

---

app/flags/adversaries/flag_2.py

verification for this flag was hitting an exception that never let it work.

Abilities have a payloads attribute, not a payload attribute

---

static/css/training.css
templates/training.html

- Banner notification for using training against tagged releases

VIRTS-1062/adding banner for only using training on tagged releases

---

app/flags/adversaries/flag_0.py
app/flags/adversaries/flag_1.py
app/flags/developers/flag_1.py

- Flags updated to reflect adversary profile change to atomic_ordering vs phases

VIRTS-1062-B/patching flags for new adversary file structure

---

templates/training.html

Small CSS change to enable newlines to show up in text. Helps provide limited formatting.

Allow newlines in challenge text

---

app/flags/plugins/gameboard/flag_0.py
app/flags/plugins/response/flag_1.py
data/9888fb54-d545-4a93-9b37-c65923565af4.yml

fixing missing space in response flag and changing gameboard flag to specify operation names

VIRTS-1157

---

app/flags/agents/blue_0.py
app/flags/agents/blue_1.py
app/flags/agents/blue_2.py
app/flags/agents/blue_3.py

Breaking the blue cert PR into a few separate PRs. This one is just the agent flags.

agent flags for blue cert

---

app/base_flag.py

Static file to hold commonly used functions to avoid repeating code through each flag that needs some sort of setup

base_flag.py

---

app/base_flag.py

Needed to specify the planner being used

fixing a bug that I thought I had already fixed

---

app/flags/plugins/response/flag_1.py

This should partly address the issue brought up in https://github.com/mitre/caldera/issues/1700

Flag should require connecting to a remote port, not just listening on local port

---

data/abilities/training/18702cd3-8e98-4eb7-99d4-0d2816926af1.yml
data/abilities/training/586140a1-9755-4996-883d-82a17c7737b2.yml
data/abilities/training/6d53c4a8-ecd3-4131-a7a2-704a5b43dd83.yml
data/abilities/training/e13c4e45-d19f-440e-8a72-fad728a1789c.yml
data/abilities/training/f0d77555-fa79-4884-8afd-73d39f887879.yml
data/abilities/training/fc4715ac-758e-4ba9-9e52-d07ff3d22a74.yml
data/adversaries/08619190-9eb5-4f35-97e1-0dafe04e0203.yml
data/adversaries/2885d0fe-60a7-469b-9e2e-a46b7be2b4df.yml
data/adversaries/2c99958e-36e0-4fab-bcdf-977926a58cd6.yml
data/adversaries/72c0b333-f6fe-4fa0-a342-4215e8de3947.yml
data/adversaries/890508db-9646-4a2d-8d1a-4ea25b3ce02a.yml
data/adversaries/9fbc7164-9175-4fc6-bb20-9669dc121df8.yml
data/payloads/phish_email.txt

Breaking out abilities, adversaries, and a payload from the blue manual flags PR.

Blue manual abilities and adversaries

---

templates/training.html

When completing a cert, the result will now look like this

adding context to cert code

---

app/flags/advanced/flag_2.py
app/flags/adversaries/flag_2.py
app/flags/agents/flag_5.py
app/flags/plugins/response/flag_0.py

Changes to training flags to make descriptions more concise.

Update Training Flag Descriptions

---

app/base_flag.py

Not a bug, really just cleaning up code that matched an older version of c_operation

Change to create_operation call to match current state of c_operation

---

app/flags/agents/flag_5.py

Update 'Bootstrap Abilities' Training Flag

---

app/flags/agents/blue_1.py
app/flags/agents/blue_3.py
app/flags/autonomous/blue_1.py

Fixed two typos. Added clarification to the "Process on Unauthorized Port" flag.

Clarifications and typos

---

__init__.py
app/c_badge.py
app/c_certification.py
app/c_flag.py
app/errors.py
app/training_api.py
hook.py
solution_guides/AdversariesFlag0.md
solution_guides/AdversariesFlag1.md
solution_guides/AdversariesFlag2.md
solution_guides/AgentsFlag0.md
solution_guides/AgentsFlag1.md
solution_guides/AgentsFlag2.md
solution_guides/AgentsFlag3.md
solution_guides/AgentsFlag4.md
solution_guides/AgentsFlag5.md
solution_guides/AgentsFlag6.md
solution_guides/AgentsFlag7.md
solution_guides/PluginsManxFlag0.md
solution_guides/PluginsManxFlag1.md
static/css/markdown.css
static/css/training.css
static/js/training.js
templates/certificate_solution_guide.html
templates/flag_solution_guide.html
templates/training.html
tests/app/test_badge.py
tests/app/test_certification.py

The markdown depdency PR in core caldera needs to be merged first: https://github.com/mitre/caldera/pull/2054
This PR adds the ability to show solutions guides for training certificates as well as individual training flags. This also adds solutions guides for a subset of the user certificate training flags.
Solutions guides are written as markdown files and located under the `solutions_guides` folder. Markdown was chosen as a means to write this guides quickly and allow for flexibility in formatting, layout, and potentially adding media in the future (images/video). Also, every developer on the project knows markdown since we all use github.
The following endpoints were added for loading html views of certificate/flag solutions guides.
* …

[VIRTS-1813] - Add training flag solution guides

---

solution_guides/AdvancedFlag0.md
solution_guides/AdvancedFlag1.md
solution_guides/AdvancedFlag2.md
solution_guides/OperationsFlag0.md
solution_guides/OperationsFlag1.md
solution_guides/OperationsFlag2.md
solution_guides/OperationsFlag3.md
solution_guides/PluginsGameboardFlag0.md
solution_guides/PluginsMockFlag0.md

Adding solution guides.
Opened each page to verify loading and formatting.

Operations, advanced, and mock plugin solutions guides

---

static/js/training.js
templates/training.html

(insert summary)
- [n/a] I have made corresponding changes to the documentation
- [n/a] I have added tests that prove my fix is effective or that my feature works

Moved certificate code alert to banner (VIRTS-1941)

---

app/flags/agents/flag_1.py
app/flags/plugins/mock/flag_0.py

Added two extra hints to help others going through training.
Ran through Caldera Training and took note to see if string changes affected loading the module
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have made corresponding changes to the documentation
- [ x ] I have added tests that prove my fix is effective or that my feature works

Changed hints to be more helpful for Remote Agent and Mock Flags

---

app/flags/adversaries/flag_2.py

Implements https://github.com/mitre/caldera/pull/2120
Check for cleanup and payloads on executor, not ability.
See: https://github.com/mitre/caldera/pull/2120

[VIRTS-1964] Ability Storage

---

solution_guides/PluginsGameboardFlag0.md

Fix wording for gameboard solution guide to use the correct operation name "Gameboard - Blue".
Viewed the updated solution guide to make sure the changes are reflected appropriately.

Fix wording for blue gameboard solution guide

---

app/flags/manual/blue_2b.py
app/flags/operations/flag_0.py
app/flags/operations/flag_1.py
app/flags/operations/flag_2.py
app/flags/plugins/manx/flag_0.py
app/flags/plugins/mock/flag_0.py

more appropriate name

---

app/flags/agents/flag_5.py
solution_guides/AgentsFlag5.md

Update Flag 5 for the new 4.0 GUI to suggest using the ability name rather than the UID.

Update flag 5 to use ability name for adding Bootstrap ability.

---

app/flags/adversaries/flag_2.py

Sync the challenge and flag checking logic for "Create ability" adversary flag.
Accomplished flag within training per challenge description.

fixed consistency between challenge and flag check

---

templates/training.html

Fixed confetti ctx errors; fixed expand flag bug

Cert fixes confetti

---

templates/training.html

The flag the user is actively trying to complete should be highlighted in red, this PR does that.
Red border appears on active cards.

Fix highlighting on active badge card

---

solution_guides/OperationsFlag0.md
solution_guides/OperationsFlag1.md
solution_guides/PluginsManxFlag0.md
solution_guides/PluginsMockFlag0.md

Change 'Hunter' adversary name to 'Ransack' in the solution guides as that adversary profile doesn't exist anymore
Ran CALDERA with the updated solution guides and verified the changes in the training plugin solution guides.

VIRTS-3812 - update Hunter references

---

templates/training.html

Updates the certificate instructions to point users to the MS Form. Once submitted, an approval request is sent to our CALDERA team, and if approved, a template is generated and sent to the user.
The form and flow work as intended, and I received the certificate after filling out the form.

Update cert link to point to MS Form

---

README.md
app/flags/advanced/flag_2.py
app/flags/adversaries/flag_1.py
app/flags/developers/flag_2.py
app/training_api.py
gui/views/training.vue
hook.py
package.json
solution_guides/AdvancedFlag2.md
solution_guides/AgentsFlag0.md
solution_guides/AgentsFlag1.md
solution_guides/AgentsFlag5.md
solution_guides/AgentsFlag6.md
solution_guides/PluginsManxFlag0.md
solution_guides/PluginsManxFlag1.md
solution_guides/PluginsResponseFlag0.md
solution_guides/PluginsResponseFlag1.md

This PR adds support to v5 by rewriting the UI in Vue

Update to Vue
