static/css/training.css

Fixes backface visibility bug in chrome browser where front of card is still visibility during a hover.

fixing chrome backface visibility bug

---

app/flags/agents/flag_2.py

It should be different from the default in https://github.com/mitre/caldera/blob/master/conf/agents.yml#L6 so users don't automatically get the flag.

Change untrusted timer target

---

app/flags/advanced/flag_1.py
app/flags/advanced/flag_2.py

Instructions for flag_1 were incorrect.
flag_2 produced errors before the 'test' user was added ("'NoneType' object is not subscriptable").

Fix Advanced flags

---

app/flags/operations/flag_3.py

The flag wasn't updated to the ad-hoc adversary change, this fixes that

adversaries without profiles now have an adversary_id of 'ad-hoc'

---

hook.py

This allows blue certs to be visible on Caldira instead of Caldera

Getting access field from cert file

---

app/flags/adversaries/flag_1.py

Issue in "Combine Adversary Profiles" flag prevents flag completion. `ability` is a string, but was treated as an object.

Fix "Combine Adversary Profiles" flag

---

app/flags/advanced/flag_2.py

Previously checked for the existence of a user with the username "test", then confirmed that the user had "red" permissions. Description additionally requested that the user use "test" as the password and that the user be logged in.
Reworked to include check for "test" as the password. Also changed the permissions check to use the "permissions" key. Removed the requirement to log in as this user, as checking this does not appear to be possible.

Reworked new user flag

---

app/flags/operations/flag_0.py
app/flags/operations/flag_1.py

The "Base64 Operation" flag specifies "At least 5 abilities should execute". Added the check to the flag. The "Basic Operation" flag does not specify a chain length, so the check has been removed.

Added chain length check to 'Base64 Operation', removed from 'Basic Op'

---

app/flags/plugins/response/flag_1.py

One of the issues with the training plugin arose because the user had multiple blue operations. This change makes that not be an issue.

can have multiple blue operations without causing issues now

---

app/base_flag.py
hook.py

Abilities, adversaries, and operations will be assigned HIDDEN access, preventing them from being visible on the front end. Relies on https://github.com/mitre/caldera/pull/1734/files

Setting all files and operations to have hidden access

---

app/flags/autonomous/blue_2.py

Flag specifies user to place malicious file in C:\Users\Public directory, as the relevant Response plugin ability now only looks in that directory. Linked to https://github.com/mitre/response/pull/48

modified flag text to specify Public user directory

---

static/js/training.js
templates/training.html

Check answers was originally in the `refresh()` function, causing answers to be checked when switching between certifications.
Check answers has been pulled out of `refresh()` and assigned to its own function to be called only when the "Check Answers" button is clicked.

Bug Fix for Check Answers

---

app/flags/agents/flag_4.py

Flag: Agent filename
File: agents/flag_4.py
Change: Changed the "super_scary.txt" requirement to "super_scary.exe". The extension is automatically appended, so setting the implant_name to "super_scary.txt" would result in an agent running as "super_scary.txt.exe".

Training updates

---

app/flags/agents/flag_0.py
app/flags/agents/flag_1.py
app/flags/agents/flag_2.py
app/flags/agents/flag_3.py
app/flags/agents/flag_4.py
app/flags/agents/flag_5.py
app/flags/agents/flag_6.py
app/flags/agents/flag_7.py
app/flags/plugins/atomic/flag_0.py
app/flags/plugins/manx/flag_0.py
app/flags/plugins/manx/flag_1.py

Fixed some unwanted line breaks and whitespace issues with training flags.
This was accomplished by replacing uses multi-line triple-quoted string literals with multi-line literals inside parentheses. I also replaced instances of `\` escaped line breaks with the parentheses-based joining.
Note that I only updated the Agent, Manx, and Atomic flags. @domainicus is going to be updating other flags under the User certificate.
I modified the `training.js` file to show all flags (i may have been able to add a certificate type to the yaml file?)  and looked at all the updated flags in my browser to verify that the text whitespace issues had been resolved.
N/A

Remove unwanted leading/trailing whitespace from Flag text sections.

---

app/flags/plugins/gameboard/flag_0.py

Fixes an issue with the gameboard flag verification, where it would return `True` even if no required operations had been created.
This is due to how `all()` functions in python when passed in an empty iterable:
```python
>>> all([])
True
```
I ran the server with `--fresh` and set up the user certificate to show me that flag (i set the `cert_type` to `exam` but there are lotsa ways to do this). I then confirmed that the gameboard plugin was not auto-completed like it was before. I then went through the flag steps and verified that the flag did not complete until both operations had been created.

Fix bug with Gameboard flag verification

---

data/certifications/9cd5f3a0-765d-45bc-85c2-bc76d4282599.yml

This PR disables the Compass training flag in the User certification. We are going to be reworking this flag in VIRTS-1847.
After making the change I restarted the server and verified that the flag and badge disappeared from the user certification.

[VIRTS-1891] Disable the compass training flag in the user certificate.

---

static/css/training.css

(insert summary)
Ran Caldera app locally on Chrome browser, and verified text overflow bug has been fixed with responsive card heights.

[VIRTS-1915] Added media queries to fix overflow of text in training cards

---

app/flags/attack/blue_4.py

In the Entreprise layer, Lateral tool transfer (T1570) is closer to the procedure suggested and T1544 (in the comment in the code) is only visible in the mobile layer; and as the procedure suggests the windows sandcat agent, I first did not thin to change to the mobile layer to find the remote copy technique.
no test were run it's just about changing the answer for the quiz

BLUE ATT@CK QUIZ 5 Answer

---

templates/training.html

Tweaks the padding on the badge row to allow for more space at the top, and changes the sizing on the flag badges so they look cleaner and fit within the SVG.
Layout and badges look less cluttered and more neat.

Make minor changes to padding on flag badges

---

app/flags/operations/flag_0.py
app/flags/operations/flag_1.py
app/flags/operations/flag_2.py
app/flags/plugins/manx/flag_0.py
app/flags/plugins/mock/flag_0.py
solution_guides/OperationsFlag0.md
solution_guides/OperationsFlag1.md
solution_guides/PluginsManxFlag0.md
solution_guides/PluginsMockFlag0.md

`Ransack` adversary profile can take a large amount of time to complete due to copious amounts of recursive process enumeration. Changing to `Check` profile has fewer recursive enumeration steps, thus will complete faster.
Verified that the `Check` adversary id (01d77744-2515-401a-a497-d9f7241aac3c) located in `stockpile` matched the changes. Ran training plugin with changed adversary and verified that flags would trigger.

Operation change from ransack to check
